### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by zhuzhen1735** [joyjitchatterjee/XAI4Wind#2]
where can i get this file
![image](https://github.com/joyjitchatterjee/XAI4Wind/assets/104407004/8118eec1-51f5-44b8-ab04-82a5dc8ebadd)

**Comment by joyjitchatterjee** [comment]
Hello,Thanks for your interest. As you may have seen in the repository’s readme section - “Due to confidentiality reasons, we have not provided the numeric values and complete SCADA corpus, but only released information which is presently in the public domain in this repository.”The full pre-processed SCADA dataset with fault labels and numeric values of SCADA parameters that you are referring to for the dataframe is from the industry and is unfortunately thus not publicly available with the repository. We could only publicly share the other materials for the knowledge graph in the repository - and hope that the graph can be integrated with any other types of data that a user has available serving as an overall framework.Thanks again for your message,Dr. Joyjit ChatterjeeOn 2 Aug 2023, at 08:24, zhuzhen1735 ***@***.***> wrote:﻿
where can i get this file

**Comment by zhuzhen1735** [comment]
Thank you for your reply. Could you please provide me with the header and first few rows of data for my reference? If possible, I would greatly appreciate it.

**Comment by joyjitchatterjee** [comment]
Hi,While I cannot unfortunately directly share this preprocessed dataset or few rows due to reasons mentioned above, I can point you to an open source dataset that has historical failure records and SCADA data for wind farms to download free of cost.Dataedp.comWhile the knowledge graph may not be directly integrated into this data, I still hope that it will help you in using it for further integration with some modifications you can perform to this data. Hope this helps.On 2 Aug 2023, at 09:38, zhuzhen1735 ***@***.***> wrote:﻿
Thank you for your reply. Could you please provide me with the header and first few rows of data for my reference? If possible, I would greatly appreciate it.

**Comment by zhuzhen1735** [comment]
I sincerely thank you for your prompt response and valuable assistance in my request.And thank you for your time, attention, and generosity in sharing relevant data. I am truly grateful for your support and cooperation. I look forward to the opportunity of further collaboration or guidance in the future.Wishing you continued success in all your endeavors.

**Comment by joyjitchatterjee** [comment]
https://www.edp.com/en/innovation/open-data/data has some example data (from a different wind farm) to given an idea of how SCADA data and fault logs in a wind turbine look like. This can be integrated by modifying the existing knowledge graph or creating a new one based on this open source dataset.
